apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: messages.pagercontroller.swine.dev
  labels:
    app: strimzi
spec:
  group: pagercontroller.swine.dev
  versions:
  - name: v1alpha1
    served: true
    storage: true
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Message
    listKind: MessageList
    singular: message
    plural: messages
    shortNames:
    - msg
  additionalPrinterColumns:
  - name: Desired replicas
    description: The desired number of Kafka Bridge replicas
    JSONPath: .spec.replicas
    type: integer
  - name: Bootstrap Servers
    description: The boostrap servers
    JSONPath: .spec.bootstrapServers
    type: string
    priority: 1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            replicas:
              type: integer
              minimum: 0
        status:
          type: object
          properties:
            observedGeneration:
              type: integer
            url:
              type: string
