apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: messages.pagercontroller.swine.dev
  labels:
    app: strimzi
spec:
  group: pagercontroller.swine.dev
  versions:
  - name: v1alpha1
    served: true
    storage: true
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Message
    listKind: MessageList
    singular: message
    plural: messages
    shortNames:
    - msg
  additionalPrinterColumns:
  - name: Channel
    description: The channel to post the message
    JSONPath: .spec.channel
    type: string
    priority: 5
  - name: Text
    description: The text to post
    JSONPath: .spec.text
    type: string
    priority: 10
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            channel:
              type: string
            text:
              type: string
        status:
          type: object
          properties:
            observedGeneration:
              type: integer
            url:
              type: string
